version: '{build}'

image: Visual Studio 2017
configuration: Release

before_build:
- dotnet restore

build:
  verbosity: minimal

artifacts:
- path: YoutubeExplode.Converter\bin\$(configuration)\YoutubeExplode.Converter*.nupkg
  name: YoutubeExplode.Converter.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 5VyEaGo5gRLr9HdkRFqS1enRq+K8Qarg1dzU33CE1dOmVXp43JaS2PQTNgsRHXkc
  artifact: YoutubeExplode.Converter.nupkg
  on:
    branch: master
    appveyor_repo_tag: true