version: '{build}'

image: Visual Studio 2017
configuration: Release

before_build:
- dotnet restore

build:
  verbosity: minimal

artifacts:
- path: YoutubeExplode.Converter\bin\$(configuration)\YoutubeExplode.Converter*.nupkg
  name: YoutubeExplode.Converter.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: QuL5btMfw2HUtOrAO0C8hw0ILWLAY9Tq4Gp1uuDiPCjkOt7H8glITwlPCxoB/WWA
  artifact: YoutubeExplode.Converter.nupkg
  on:
    branch: master
    appveyor_repo_tag: true